### ISSUE TITLE
bin/setup should include db:migrate or db:setup

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-myjobs#209]
The `bin/setup` for this app doesn't have any provision for getting the database up and running.

I suspect that this will require checking for the existence of a database and then running the command if it's not found.

**Comment by ericfranz** [comment]
The way the script is right now, you can run bin/setup over and over again with the same app, changing env vars you provide to it, without touching the database. This is nice.

So we would only do this if there was an easy and reliable way to check if the database exists. Then at the bottom we can do something like:

```ruby
if APP.development? && database_does_not_exist
  // db:setup
end
```

**Comment by MorganRodgers** [comment]
People keep deleting their database. Since users are visiting the app URLs directly each app must ensure its own database.

**Comment by ericfranz** [comment]
This is the wrong issue. "Since users are visiting the app URLs directly each app must ensure its own database." The Job Composer creates per-user databases using the per-user-setup script (which maybe should be renamed to `per-user-setup`) https://github.com/OSC/ood-myjobs/blob/master/bin/setup-production.

I'll close this one. The per user setup script does create the database if it doesn't exist, but only when accessing through the dashboard. Moving the responsibility of running the per user setup from the Dashboard to the app itself (in a bin/ruby wrapper, or maybe there is a Passenger hook to do this) may be appropriate but is a separate issue.
