### ISSUE TITLE
Incorrect links when select different job

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-myjobs#226]
This occurs if there is a long delay for AJAX requests.

How to reproduce:

1. Select a job in the table.
2. Notice the script in the bottom right corner with links to "Open Editor", ...
3. Select another job (with long AJAX delay).
4. Click "Open Editor" or any other link in bottom right corner, it takes you to the previous job's files.

The Arizona site can sometimes take awhile for the AJAX to update and this caused me to edit the wrong scripts a few times.

**Comment by brianmcmichael** [comment]
This was introduced when we eliminated the "blink" effect observed when switching or reloading data panels. Rather than hide the old data, the panel would stay in place until the new data is rendered.

To fix this, we may need to fill the panel with blank strings while reloading, then repopulate them when the data arrives from remote. This would disallow selecting stale data, but also prevent the blinking panel.

**Comment by nickjer** [comment]
Another possible option is to disable the buttons and show a spinning icon in the panel header so that users are aware that the data is being refreshed.
